version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  events-commands:
    volumes:
        - ./gateway/:/mnt/
    build: ./gateway
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    depends_on:
      - events-commands
